### ISSUE TITLE
Missing module when calling the get-intunereport cmdlet

### ISSUE THREAD

**Issue by carvan** [ztrhgf/useful_powershell_modules#2]
Hi!

first off I wanted to thank for this useful module. I wanted also to report an issue with it when running the Get-IntuneReport cmdlet:
`Import-Module : The specified module 'Variables' was not loaded because no valid module file was found in any module
directory`

It looks like it's loading a module which is not in the IntuneStuff module...

**Comment by ztrhgf** [comment]
Should be fixed with new 1.3.1 IntuneStuff module version

**Comment by carvan** [comment]
Thanks! I might be doing something wrong, I'm not getting the missing module error anymore, but that cmdlet doesn't work still: 
![image](https://github.com/ztrhgf/useful_powershell_modules/assets/11394057/2d04d6a9-7604-478e-a260-b15cc8252f1a)

**Comment by ztrhgf** [comment]
I see. Specify 'header' parameter too for now. I need some time to fix this issue.

So create service principal with following graph api permissions (as stated in function NOTES help section):
Application.Read.All
    Device.Read.All
    DeviceManagementApps.Read.All
    DeviceManagementConfiguration.Read.All
    DeviceManagementManagedDevices.Read.All
    ProgramControl.Read.All
    Reports.Read.All

Create authentication header using this service principal credentials like:
$header = New-GraphAPIAuthHeader -credential (get-credential)

Call:
Get-IntuneReport -header $header -reportName AppInstallStatusAggregate

**Comment by carvan** [comment]
Perfect, thank you. I'll give it a try as soon as possibile.
