### ISSUE TITLE
connect-msgraph - intune module - PS7

### ISSUE THREAD

**Issue by dandirk** [ztrhgf/useful_powershell_modules#3]
Nice module!  The device policy features was especially useful.

Though I ran into issues running it with PS 7...

Well not your part of the module but connect-msgraph included in the intune module.

When I just run the cmdlet to interactively auth receive the following in PS7 but not 5.  Haven't dug into it really to see if workstation or other cause but as the intune module sadly hasn't been updated in 4 years figured it might just be incompatible.

Connect-MSGraph: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by ztrhgf** [comment]
Sorry, I am not using Core version at all, so have no idea.
