### ISSUE TITLE
Get-CorrespondingGraphCommand incorrect Table headers 

### ISSUE THREAD

**Issue by ITMonkey78** [ztrhgf/useful_powershell_modules#5]
last line of the code

Microsoft appear to have changed the Header names on the source page so the $table values containing the command maps are now headed differently.

So $_."Azure AD cmdlets" should be $_."Azure AD cmdlet" and $_."Microsoft Graph PowerShell cmdlets" should be $_."Microsoft Graph PowerShell cmdlet"

**Comment by ztrhgf** [comment]
Fixed in new 1.1.1 module version. Thanks for pointing this out 👍.

Also fixed added footnotes
![image](https://github.com/ztrhgf/useful_powershell_modules/assets/2930419/28a88484-4b0a-4208-bfff-d5b9d57099b0)
