### ISSUE TITLE
Question: I've a custom module (as ZIP) which command to use to upload a new Zip of the module?

### ISSUE THREAD

**Issue by RonKoppelaar** [ztrhgf/useful_powershell_modules#8]
I have a custom module (as zip file), and I would like to upload the zip file but I cant find the appropriate cmdlet.
I thought it would be: New-AzureAutomationRuntimeModule but it lacks parameter it local filepath.

**Comment by ztrhgf** [comment]
Sorry about that. I forgot to publish it. 

The function is named` New-AzureAutomationRuntimeZIPModule` and is in the [last version of the AzureResourceStuff](https://www.powershellgallery.com/packages/AzureResourceStuff/1.0.12) module now 

Thanks for reporting this!

**Comment by RonKoppelaar** [comment]
Thx for very quick answer and fix. Other parties can learn from this :-)
